src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @UniqueEntity("title")
 * @UniqueEntity("slug")
 */
class Trick
{
    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=191, unique=true)
     * @Assert\NotBlank
     * @Groups("tricks:list")
     */
    private $title;

    /**
     * @var string
     * @ORM\Column(type="string", length=191, unique=true)
     * @Groups("tricks:list")
     */
    private $slug;

    /**
     * @var string
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @var DateTimeInterface
     * @ORM\Column(type="datetime")
     */
    private $publicationDate;

    /**
     * @var DateTimeInterface
     * @ORM\Column(type="datetime")
     */
    private $lastModificationDate;

    /**
     * @var TrickGroup
     * @ORM\ManyToOne(targetEntity=TrickGroup::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TrickGroup;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="trick", orphanRemoval=true)
     */
    private $comments;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity=TrickImage::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     * @Groups("tricks:list")
     */
    private $images;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity=TrickVideo::class, mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\OneToOne(targetEntity=TrickMainImage::class, mappedBy="trickOwner", cascade={"persist", "remove"})
     * @Groups("tricks:list")
     */
    private $mainImage;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("tricks:list")
     */
    private $author;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->publicationDate = $this->lastModificationDate = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublicationDate(): ?DateTimeInterface
    {
        return $this->publicationDate;
    }

    public function setPublicationDate(DateTimeInterface $publicationDate): self
    {
        $this->publicationDate = $publicationDate;

        return $this;
    }

    public function getLastModificationDate(): ?DateTimeInterface
    {
        return $this->lastModificationDate;
    }

    public function setLastModificationDate(DateTimeInterface $lastModificationDate): self
    {
        $this->lastModificationDate = $lastModificationDate;

        return $this;
    }

    public function getTrickGroup(): ?TrickGroup
    {
        return $this->TrickGroup;
    }

    public function setTrickGroup(?TrickGroup $TrickGroup): self
    {
        $this->TrickGroup = $TrickGroup;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TrickImage[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(TrickImage $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(TrickImage $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TrickVideo[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(TrickVideo $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(TrickVideo $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getMainImage(): ?TrickMainImage
    {
        return $this->mainImage;
    }

    public function setMainImage(?TrickMainImage $mainImage): self
    {
        $this->mainImage = $mainImage;

        // set (or unset) the owning side of the relation if necessary
        $newTrick = null === $mainImage ? null : $this;
        if ($mainImage && $mainImage->getTrickOwner() !== $newTrick) {
            $mainImage->setTrickOwner($newTrick);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?UserInterface $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Form\CommentType;
use App\Form\NewTrickType;
use App\Form\NewVideoType;
use App\Repository\TrickRepository;
use App\Service\TrickFormHandler;
use Embed\Embed;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tricks")
 */
class TrickController extends AbstractController
{
    /**
     * @Route("/", name="trick_index", methods={"GET"})
     * @param TrickRepository $trickRepository
     * @param Request $request
     * @return Response
     */
    public function index(TrickRepository $trickRepository, Request $request): Response
    {
        $page = $request->query->get('page');

        if ($page === null) {
            return $this->render('trick/index.html.twig', [
                'tricks' => $trickRepository->findPage(1),
            ]);
        }

        if ($page < 1) {
            throw new BadRequestHttpException();
        }

        $results = $trickRepository->findPage((int) $page);

        return $this->json(["items" => $results], 200, [], ['groups' => ['tricks:list']]);
    }

    /**
     * @Route("/new", name="trick_new", methods={"GET", "POST"})
     * @param Request $request
     * @return Response
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    public function new(Request $request, TrickFormHandler $trickFormHandler): Response
    {
        $trick = new Trick();
        $form = $this->createForm(NewTrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trick->setAuthor($this->getUser());
            $trickFormHandler->handleFormSubmission($form, $trick);
            $this->addFlash('success', 'Your trick has correctly been created.');
            return $this->redirectToRoute('trick_index');
        }

        $modalForm = $this->createForm(NewVideoType::class, null, [
            'action' => $this->generateUrl('get_video_thumbnail'),
            'method' => 'GET',
        ]);

        return $this->render('trick/new.html.twig', [
            'form' => $form->createView(),
            'modalForm' => $modalForm->createView(),
        ]);
    }

    /**
     * @Route("/details/{slug}", name="trick_show", methods={"GET"})
     * @param Trick $trick
     * @return Response
     */
    public function show(Trick $trick): Response
    {
        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment, [
            'action' => $this->generateUrl('comment_new', ['trickSlug' => $trick->getSlug()]),
        ]);

        $comments = $this->getDoctrine()->getRepository(Comment::class)->findBy(['trick' => $trick], ['id' => 'DESC'], 10);

        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'commentForm' => $commentForm->createView(),
            'comments' => $comments,
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="trick_edit", methods={"GET", "PUT"})
     * @param Request $request
     * @param Trick $trick
     * @return Response
     * @IsGranted("IS_TRICK_OWNER", subject="trick")
     */
    public function edit(Request $request, Trick $trick, TrickFormHandler $trickFormHandler): Response
    {
        $form = $this->createForm(NewTrickType::class, $trick, [
            'method' => 'PUT',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trickFormHandler->handleFormSubmission($form, $trick);
            return $this->redirectToRoute('trick_show', ['slug' => $trick->getSlug()]);
        }

        $modalForm = $this->createForm(NewVideoType::class, null, [
            'action' => $this->generateUrl('get_video_thumbnail'),
            'method' => 'GET',
        ]);

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
            'modalForm' => $modalForm->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="trick_delete", methods={"DELETE"})
     * @param Request $request
     * @param Trick $trick
     * @return Response
     * @IsGranted("IS_TRICK_OWNER", subject="trick")
     */
    public function delete(Request $request, Trick $trick): Response
    {
        if ($this->isCsrfTokenValid('deleteTrick', $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($trick);
            $entityManager->flush();
            return new Response(null, 204);
        }

        throw new AccessDeniedHttpException();
    }

    /**
     * @Route("/getVideoThumbnail", name="get_video_thumbnail", methods={"POST"})
     * @param Request $request
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @return Response|NotFoundHttpException
     */
    public function getVideoThumbnail(Request $request)
    {
        $form = $this->createForm(NewVideoType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $videoUrl = $form['url']->getData();
            $embed = new Embed();
            $info = $embed->get($videoUrl);
            return new Response($info->image);
        }

        return new NotFoundHttpException();
    }
}

templates/trick/_delete_form.html.twig
<form method="post" action="{{ path('trick_delete', {'slug': trick.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
    <button class="btn">Delete</button>
</form>

templates/trick/_delete_modal.html.twig
{% block delete_modal %}
<div id="delete-modal" class="modal">
    <div class="modal-background"></div>
    <div class="modal-content">
        <div class="box has-text-centered">
            <h2 class="title is-4">Do you really want to delete this trick?</h2>
            <div class="buttons is-centered">
                <button id="cancel-button" class="button">No, cancel!</button>
                <button id="delete-button" class="button is-danger" data-link="" data-token="">Yes, delete it!</button>
            </div>
        </div>
    </div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>
{% endblock %}

templates/trick/_form.html.twig
{{ form_start(form) }}
<div class="card-image has-text-centered has-background-light">
    <figure id="trick-details-figure" class="image is-16by9">
        <div class="file field field-container is-right is-primary">
            <label class="file-label">
                {{ form_widget(form.mainImage) }}
                <span class="file-cta icon-container">
                    <span class="file-icon add is-marginless">
                        <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-icon change is-marginless is-hidden">
                        <i class="fas fa-pen"></i>
                    </span>
                </span>
                <span class="file-name input-text">Add a main image</span>
            </label>
            <button type="button" class="button trash icon-container is-marginless is-danger is-small is-hidden"><span class="file-icon trash is-marginless">
                        <i class="fas fa-trash"></i>
            </span></button>
        </div>
        <img id="trick-main-image" src="{% if trick is defined and trick.mainImage is not empty %}{{ asset("uploads/images/#{trick.mainImage.fileName}") }}{% endif %}" alt="">
    </figure>
    <h1 class="title has-text-dark text-centered-on-image">{% block trick_title %}Main Image{% endblock %}</h1>
</div>
<div class="card-content">
    <div class="content">
        <div id="button-toggle-media" class="buttons is-centered is-hidden-tablet">
            <button type="button" class="button is-primary">See medias</button>
        </div>
        <div id="medias-container" class="columns is-hidden-mobile">
            <div
                    id="trick-details-images-container"
                    class="column is-6 columns is-multiline"
                    data-prototype="{{ form_widget(form.images.vars.prototype)|e }}"
                    data-widget-counter="{{ form.images|length }}"
            >
                {% for imageField in form.images %}
                    {% include('/trick/_form_image_template.html.twig') %}
                {% endfor %}

            </div>
            <div
                    id="trick-details-videos-container"
                    class="column is-6 columns is-multiline"
                    data-prototype="{{ form_widget(form.videos.vars.prototype)|e }}"
                    data-widget-counter="{{ form.videos|length }}"
            >
                {% for videoField in form.videos %}
                    {% include('/trick/_form_videos_template.html.twig') %}
                {% endfor %}
            </div>
        </div>
        <div class="columns is-centered">
            <div class="column is-8">
                {{ form_row(form.title) }}
                {{ form_row(form.description) }}
                {{ form_row(form.TrickGroup) }}
                {{ form_row(form._token) }}
                <div class="field is-grouped is-grouped-right">
                    <div class="control buttons">
                        {% if "edit" in app.request.pathInfo %}
                            <button type="button" class="button is-danger delete-trick"
                                    data-link="{{ path('trick_delete', {'slug': trick.slug}) }}"
                                    data-token="{{ csrf_token("deleteTrick") }}"
                            >
                                Delete
                            </button>
                        {% endif %}
                        <button class="button is-link submit" >{{ button_label|default('Save') }}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{ form_end(form, {'render_rest': false}) }}

{% block modal %}
    {% include('VideoModal/video_modal.html.twig') %}
{% endblock %}

<template id="trick-details-images-template">
    {% include('/trick/_form_image_template.html.twig') %}
</template>

<template id="trick-details-videos-template">
    {% include('/trick/_form_videos_template.html.twig') %}
</template>

templates/trick/_form_image_template.html.twig
{% block form_image_template %}
    <div class="column is-4 is-10-mobile is-offset-1-mobile has-text-centered template-content" >
        <figure>
            <img class="trick-details-thumbnail is-hidden" src="{% if imageField is defined and imageField.fileName.vars.value is not empty %}{{ asset("uploads/images/#{imageField.fileName.vars.value}") }}{% endif %}" alt="">
        </figure>
        <div class="file field-container buttons is-centered is-primary boxed is-boxed">
            <label class="file-label input-container">
                <span class="file-cta icon-container">
                    <span class="file-icon change is-marginless is-hidden">
                        <i class="fas fa-pen"></i>
                    </span>
                    <span class="file-icon add is-marginless">
                        <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label input-text">Add image</span>
                </span>
                {% if imageField is defined %}
                    {{ form_widget(imageField) }}
                {% endif %}
            </label>
            <button type="button" class="button trash icon-container is-marginless is-danger is-small is-hidden"><span class="file-icon trash is-marginless">
                        <i class="fas fa-trash"></i>
            </span></button>
        </div>
    </div>
{% endblock %}

templates/trick/_form_videos_template.html.twig
{% block form_video_template %}
    <div class="column is-4 is-10-mobile is-offset-1-mobile field-container template-content">
        {% if videoField is defined and videoField.embedCode.vars.value is not empty %}
            {{ videoField.embedCode.vars.value | raw }}
        {% endif %}
        <figure>
            <img class="trick-details-thumbnail is-hidden" src="" alt="">
        </figure>
        <div class="buttons has-addons is-centered icon-container">
            <button type="button" class="button modal-activator is-primary">
            <span class="file-icon add">
                <i class="fas fa-link"></i>
            </span>
                <span class="file-icon change is-marginless is-hidden is-small">
                        <i class="fas fa-pen"></i>
            </span>
                <span class="input-text">Add a video</span>
            </button>
            <button class="button trash icon-container is-marginless is-danger is-small is-hidden"><span
                        class="file-icon trash is-marginless">
                        <i class="fas fa-trash"></i>
            </span></button>
            <div class="input-container is-invisible">
                {% if videoField is defined %}
                    {{ form_widget(videoField) }}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/trick/_load_more_tricks.html.twig
{% block load_more_tricks_button %}
    <div class="buttons is-centered">
        <button
                id="trick-load-more-button"
                class="button is-primary"
                data-link="{{ path('trick_index') }}"
                {% if app.user %}data-user="{{ app.user.id }}{% endif %}"
                {% if is_granted('ROLE_ADMIN') %}data-is-admin="true"{% endif %}"
        >
            Load more...
        </button>
    </div>
{% endblock %}

templates/trick/_trick_card.html.twig
{% block trick_card %}
    {% if trick.mainImage is not empty %}
        {% set mainImage="/uploads/images/#{trick.mainImage.fileName}" %}
    {% elseif trick.images is not empty %}
        {% set mainImage="/uploads/images/#{trick.images['0'].fileName}" %}
    {% else %}
        {% set mainImage="/images/home_background.jpg" %}
    {% endif %}
    <div class="column is-one-third-tablet is-one-fifth-widescreen  trick-container">
        <div class="card">
            <div class="card-image">
                <figure class="image is-4by3">
                    <a href="{{ path('trick_show', {'slug': trick.slug}) }}">
                        <img src="{{ asset(mainImage) }}" alt="Image principale de {{ trick.title }}">
                    </a>
                </figure>
            </div>
            <div class="card-content">
                <div class="content columns">
                    <div class="column is-7">
                        <a href="{{ path('trick_show', {'slug': trick.slug}) }}">
                            <h2 class="title is-6">{{ trick.title }}</h2>
                        </a>
                    </div>
                        <div class="control-buttons buttons is-right column is-5 is-paddingless {% if not is_granted('IS_TRICK_OWNER', trick) %}is-hidden{% endif %}">
                            <a href="{{ path('trick_edit', {'slug': trick.slug}) }}" class="button change icon-container is-marginless is-small">
                                <span class="file-icon change is-marginless">
                                    <i class="fas fa-pen"></i>
                                </span>
                            </a>
                            <button class="button delete-trick icon-container is-marginless is-danger is-small"
                                    data-link="{{ path('trick_delete', {'slug': trick.slug}) }}"
                                    data-token="{{ csrf_token("deleteTrick") }}"
                            >
                                <span class="file-icon trash is-marginless">
                                    <i class="fas fa-trash"></i>
                                </span>
                            </button>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/trick/_trick_list.html.twig
{% block trick_list %}
    <section id="trick-cards-container" class="section is-centered columns is-marginless">
        <article class="column is-11 card px-6 py-6">
            <div id="trick-list-container" class="columns is-multiline">
                {% for trick in tricks %}
                    {{ include('trick/_trick_card.html.twig') }}
                {% endfor %}
            </div>
            {{ include('trick/_load_more_tricks.html.twig') }}
            <div id="arrow-up" class="content has-text-right is-hidden">
                <a href="#trick-cards-container"><span class="icon has-text-info is-large"><i class="fas fa-arrow-up fa-3x"></i></span></a>
            </div>
        </article>
    </section>
    {{ include('trick/_delete_modal.html.twig') }}
{% endblock%}

templates/trick/edit.html.twig
{% extends 'trick_detail_page_template.html.twig' %}

{% block title %}Edit {{ trick.title }}{% endblock %}

{% block trick_card %}
    {{ include('trick/_form.html.twig') }}
    {{ include('trick/_delete_modal.html.twig') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('trick_form') }}
    {{ encore_entry_script_tags('delete_trick') }}
    {{ encore_entry_script_tags('toggle_medias') }}
{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des tricks{% endblock %}

{% block body %}
    {{ include('trick/_trick_list.html.twig') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('fetch_tricks') }}
{% endblock %}

templates/trick/new.html.twig
{% extends 'trick_detail_page_template.html.twig' %}

{% block title %}New Trick{% endblock %}

{% block trick_card %}
        {{ include('trick/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
        {{ parent() }}
        {{ encore_entry_script_tags('trick_form') }}
{% endblock %}

templates/trick/show.html.twig
{% extends 'trick_detail_page_template.html.twig' %}

{% block title %}{{ trick.title }}{% endblock %}

{% if trick.mainImage is not empty %}
    {% set mainImage="/uploads/images/#{trick.mainImage.fileName}" %}
{% elseif trick.images is not empty %}
    {% set mainImage="/uploads/images/#{trick.images['0'].fileName}" %}
{% else %}
    {% set mainImage="/images/home_background.jpg" %}
{% endif %}

{% block trick_card %}
    <div class="card-image has-text-centered has-background-light">
        <figure id="trick-details-figure" class="image is-16by9">
            {% if is_granted("IS_AUTHENTICATED_FULLY") %}
                <div class="buttons">
                    <a href="{{ path('trick_edit', {'slug': trick.slug}) }}" class="button change icon-container is-marginless is-small"><span class="icon change is-marginless">
                            <i class="fas fa-pen"></i>
                </span></a>
                    <button class="button delete-trick icon-container is-marginless is-danger is-small"
                            data-link="{{ path('trick_delete', {'slug': trick.slug}) }}"
                            data-token="{{ csrf_token("deleteTrick") }}">
                            <span class="file-icon trash is-marginless">
                                <i class="fas fa-trash"></i>
                            </span>
                    </button>
                </div>
            {% endif %}
            <img id="trick-main-image" src="{{ asset(mainImage) }}" alt="">
        </figure>
        <h1 class="title has-text-primary text-centered-on-image">{% block trick_title %}{{ trick.title }}{% endblock %}</h1>
    </div>
    <div class="card-content">
        <div class="content">
            <div id="button-toggle-media" class="buttons is-centered is-hidden-tablet">
                <button class="button is-primary">See medias</button>
            </div>
            <div id="medias-container" class="columns is-hidden-mobile">
                <div id="trick-details-images-container" class="column is-6 columns is-multiline">
                    {% for image in trick.images %}
                        <div class="column is-4" >
                            <a href="{{ asset("/uploads/images/#{image.fileName}") }}"><figure>
                                    <img class="trick-details-thumbnail" src="{{ asset("/uploads/images/#{image.fileName}") }}" alt="">
                                </figure></a>
                        </div>
                    {% endfor %}
                </div>
                <div id="trick-details-videos-container" class="column is-6 columns is-multiline">
                    {% for video in trick.videos %}
                        <div class="column is-4 video">
                            {{ video.embedCode | raw }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="columns is-centered">
                <div class="column is-10">{{ trick.description }}</div>
            </div>
            <div class="columns is-centered">
                <div class="column is-8 is-centered are-medium tags">
                    <span class="tag">Publié le {{ trick.publicationDate|date('d/m/Y') }}</span>
                    {% if trick.publicationDate|date('d/m/Y') != trick.lastModificationDate|date('d/m/Y') %}
                        <span class="tag">Modifié le {{ trick.lastModificationDate|date('d/m/Y') }}</span>
                    {% endif %}
                    <span class="tag">{{ trick.trickGroup.name }}</span>
                </div>
            </div>
            {% if is_granted("IS_AUTHENTICATED_FULLY") %}
                <div class="columns is-centered">
                    <div class="column is-8">
                        <hr>
                    </div>
                </div>
                <div class="columns is-centered">
                    <div class="column is-8">
                        {{ include('comment/new.html.twig') }}
                    </div>
                </div>
            {% endif %}
            {% if comments is not empty %}
                <div class="columns is-centered">
                    <div class="column is-8">
                        <hr>
                    </div>
                </div>
                <div id="comment-list-container">
                    {% for comment in comments %}
                        <div class="columns is-centered comment-container">
                            <div class="column is-8">
                                {{ include('comment/show.html.twig') }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="buttons is-centered">
                    <button id="comment-load-more-button" class="button is-primary" data-link="{{ path('comment_fetch_page', {'trickSlug': trick.slug}) }}">Load more...</button>
                </div>
            {% endif %}
        </div>
    </div>
    {{ include('trick/_delete_modal.html.twig') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('delete_trick') }}
    {{ encore_entry_script_tags('toggle_medias') }}
    {{ encore_entry_script_tags('fetch_comments') }}
{% endblock %}